USE [master]
GO

/****** Object:  Database [FlightBook]    Script Date: 7/22/2022 5:58:52 PM ******/
CREATE DATABASE [FlightBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FlightBook', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FlightBook.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FlightBook_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FlightBook_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FlightBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FlightBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FlightBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FlightBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FlightBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FlightBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [FlightBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FlightBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FlightBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FlightBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FlightBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FlightBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FlightBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FlightBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FlightBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FlightBook] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FlightBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FlightBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FlightBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FlightBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FlightBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FlightBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FlightBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FlightBook] SET RECOVERY FULL 
GO

ALTER DATABASE [FlightBook] SET  MULTI_USER 
GO

ALTER DATABASE [FlightBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FlightBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FlightBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FlightBook] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FlightBook] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FlightBook] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FlightBook] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FlightBook] SET  READ_WRITE 
GO

